### ISSUE TITLE
inviter gem depends on rails 5.1.4

### ISSUE THREAD

**Issue by cdrani** [mjmorales/inviter#1]
This gem seems to be exactly what I need, but I run into this error:
```
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (~> 5.2.1)

    inviter was resolved to 0.2.0, which depends on
      rails (~> 5.1.4)
```
Please excuse my naivete, but is the fix as simple as updating the rails dependency version or is there a different solution?

**Comment by mjmorales** [comment]
Sorry for the extremely late reply. Seems I need to bump the version dependency within the gemspec.

**Comment by mjmorales** [comment]
https://github.com/mjmorales/inviter/pull/2
